version: "3.7"
services:

# cloud Kafka broker

  cloud-zookeeper:
    image: 'bitnami/zookeeper'
#    ports:
#      - '${CLOUD_ZOOKEEPER_EXT_PORT}:2181'
    volumes:
      - './data/cloud-zookeeper:/bitnami:rw'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  cloud-kafka:
    image: 'bitnami/kafka'
    ports:
      - '${CLOUD_KAFKA_INT_PORT}:${CLOUD_KAFKA_INT_PORT}'
      - '${CLOUD_KAFKA_EXT_PORT}:${CLOUD_KAFKA_EXT_PORT}'
    volumes:
      - './data/cloud-kafka:/bitnami:rw'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=cloud-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${CLOUD_KAFKA_INT_PORT},PLAINTEXT_HOST://:${CLOUD_KAFKA_EXT_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://cloud-kafka:${CLOUD_KAFKA_INT_PORT},PLAINTEXT_HOST://localhost:${CLOUD_KAFKA_EXT_PORT}
    depends_on:
      - cloud-zookeeper
      
# edge Kafka broker

  edge-zookeeper:
    image: 'bitnami/zookeeper'
#    ports:
#      - '${EDGE_ZOOKEEPER_EXT_PORT}:2181'
    volumes:
      - './data/edge-zookeeper:/bitnami:rw'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  edge-kafka:
    image: 'bitnami/kafka'
    ports:
      - '${EDGE_KAFKA_INT_PORT}:${EDGE_KAFKA_INT_PORT}'
      - '${EDGE_KAFKA_EXT_PORT}:${EDGE_KAFKA_EXT_PORT}'
    volumes:
      - './data/edge-kafka:/bitnami:rw'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=edge-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${EDGE_KAFKA_INT_PORT},PLAINTEXT_HOST://:${EDGE_KAFKA_EXT_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://edge-kafka:${EDGE_KAFKA_INT_PORT},PLAINTEXT_HOST://localhost:${EDGE_KAFKA_EXT_PORT}
    depends_on:
      - edge-zookeeper
      
# kafka-repeater from cloud to edge

  input-repeater:
    build: ./kafka-repeater
    image: iot-edge-kafka-repeater
    environment:
      - KR_HOST_FROM=cloud-kafka
      - KR_PORT_FROM=${CLOUD_KAFKA_INT_PORT}
#      - KR_GROUP_ID_FROM=123
      - KR_HOST_TO=edge-kafka
      - KR_PORT_TO=${EDGE_KAFKA_INT_PORT}
      - KR_TOPIC_FROM=${CLOUD_KAFKA_INPUT_TOPIC}
      - KR_TOPIC_TO=edge-input
    depends_on:
      - cloud-kafka
      - edge-kafka
      
# kafka-repeater from edge to cloud

  output-repeater:
    image: iot-edge-kafka-repeater
    environment:
      - KR_HOST_FROM=edge-kafka
      - KR_PORT_FROM=${EDGE_KAFKA_INT_PORT}
#      - KR_GROUP_ID_FROM=123
      - KR_HOST_TO=cloud-kafka
      - KR_PORT_TO=${CLOUD_KAFKA_INT_PORT}
      - KR_TOPIC_FROM=edge-output
      - KR_TOPIC_TO=${CLOUD_KAFKA_OUTPUT_TOPIC}
    depends_on:
      - cloud-kafka
      - edge-kafka
  